apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course
  template:
    metadata:
      labels:
        app: course
    spec:
      containers:
      - name: auth
        image: sstbappu/course-service:latest
        ports:
        - containerPort: 8080